---
x-api-blueprint:
  resource_section: name_uri
  action_section: name_method
  attributes: true
swagger: '2.0'
info:
    title: PayProp API Version 1.0
    version: "1.0"
    description: |
        This is an example

schemes:
    - https
basePath: /api/v1.0
consumes:
    - application/json
produces:
    - application/json
paths:
    /me:
        x-api-blueprint:
            group: Access Token Owner
            summary: Me
            description:
            group_description: |
                The details of the user account
        get:
            operationId: from_token
            summary: get user details
            description: |
                The response data will depend on the user type. When the user is linked to an Agency the response will contain the details of that Agency
            tags:
                - User
            responses:
                200:
                    description: Profile information for a user
                    schema:
                        type: object
                        $ref: '#/definitions/Profile'
    /agencies:
        x-api-blueprint:
            group: Agencies
            summary: Agencies
            description:
            group_description: |
                A list of agencies linked to the user account
        get:
            summary: get all agency details
            description:
            parameters:
                - name: username
                  in: query
                  description: Search for agencies by username
                  required: false
                  type: string
                - name: category
                  in: query
                  description: Search for agencies by category
                  required: false
                  type: string
                - name: subdomain
                  in: query
                  description: Search for agencies by subdomain
                  required: false
                  type: string
                - name: currency
                  in: query
                  description: Search for agencies by currency
                  required: false
                  type: string
                - name: country_code
                  in: query
                  description: Search for agencies by country code
                  required: false
                  type: string
                - name: first_line
                  in: query
                  description: Search for agencies by first line
                  required: false
                  type: string
                - name: state
                  in: query
                  description: Search for agencies by state
                  required: false
                  type: string
                - name: city
                  in: query
                  description: Search for agencies by city
                  required: false
                  type: string
                - name: zip_code
                  in: query
                  description: Search for agencies by zip code
                  required: false
                  type: string
                - name: rows
                  in: query
                  description: Restrict rows returned
                  required: false
                  type: integer
                - name: page
                  in: query
                  description: Return given page number
                  required: false
                  type: integer
            operationId: get_all
            tags:
                - Agency
            responses:
                200:
                    description: A list of agency objects
                    schema:
                        type: object
                        properties:
                            items:
                                description: List of agencies
                                type: array
                                items:
                                    $ref: '#/definitions/Agency'
    "/agencies/{external_id}":
        x-api-blueprint:
            group: Agencies
            summary: Agency
            description:
            group_description: |
                The agency linked to the user account
        get:
            summary: get agency details
            description: |
                Returns the agency linked to the passed external_id

            operationId: get
            parameters:
                - name: external_id
                  in: path
                  description: External ID of agency
                  type: string
                  required: true
            tags:
                - Agency
            responses:
                200:
                    description: A list of agency objects
                    schema:
                        type: object
                        properties:
                            items:
                                description: List of agencies
                                type: array
                                items:
                                    $ref: '#/definitions/Agency'
definitions:
    Address:
        type: object
        properties:
            city:
                type: string
            country_code:
                type: string
            created:
                type: string
                format: dateTime
            email:
                type: string
            fax:
                type: string
            first_line:
                type: string
            id:
                type: string
            latitude:
                type: string
            longitude:
                type: string
            modified:
                type: string
                format: dateTime
            phone:
                type: string
            second_line:
                type: string
            state:
                type: string
            third_line:
                type: string
            zip_code:
                type: string
    Agency:
        type: object
        properties:
            account_status:
                type: string
            activation_date:
                type: string
                format: dateTime
            address:
                type: object
                properties:
                    billing:
                        type: object
                        $ref: '#/definitions/Address'
                    statement:
                        type: object
                        $ref: '#/definitions/Address'
            affiliation_number:
                type: string
            arlan_number:
                type: string
            bill_monthly:
                type: boolean
            category:
                type: string
            company_name:
                type: string
            context:
                type: string
            country_code:
                type: string
            currency:
                type: string
            debit_payment_delay:
                type: string
            depost_reference_prefix:
                type: string
            financial_year_end:
                type: string
                format: dateTime
            formula_fee:
                type: object
                properties:
                    discount:
                        type: number
                    percentage:
                        type: number
            id:
                type: string
            landlord_statement_day:
                type: number
            monthly_turnover:
                type: number
            name:
                type: string
            name_on_sms:
                type: string
            notifications:
                type: object
                properties:
                    email:
                        type: boolean
                    sms:
                        type: boolean
            payments:
                type: object
                properties:
                    enable:
                        type: boolean
                    verify:
                        type: boolean
            portfolio_size:
                type: number
            registration:
                type: object
                properties:
                    company_number:
                        type: string
                    date:
                        type: string
                        format: dateTime
            tenant_statement_date:
                type: number
            user:
                type: object
                properties:
                    cell_phone:
                        type: string
                    email:
                        type: string
                    first_name:
                        type: string
                    last_name:
                        type: string
            username:
                type: string
            vat_number:
                type: string
            web_address:
                type: string
    Profile:
        type: object
        properties:
            user:
                type: object
                $ref: '#/definitions/User'
            scopes:
                type: array
                items:
                    type: string
            agency:
                type: object
                properties:
                    id:
                        type: string
                    name:
                        type: string
        required:
            - user
            - scopes
    User:
        type: object
        properties:
            id:
                type: string
                description: ID of the PayProp user.
            full_name:
                type: string
                description: Full name of the PayProp user.
            email_address:
                type: string
                description: Email address of the PayProp user
    Error:
        type: string
